# Main application properties
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=always

# PostgreSQL for local development
spring.datasource.url=jdbc:postgresql://localhost:5432/shareit
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=password

# Logging
logging.level.org.springframework.orm.jpa=INFO
logging.level.org.springframework.transaction=INFO